### ISSUE TITLE
Doesn't work for 'Reply to All'

### ISSUE THREAD

**Issue by jdwisc** [Vikasg7/UnQuote-for-Gmail#1]
Hi,

This extension has a lot potential and could save me a lot of trouble.  It does not seem to work when replying to all though.  I have tested it out using the reply button, but cannot get it to work with the reply to all email type.  Thank you!

**Comment by Vikasg7** [comment]
I will see what I can do in this regard.

**Comment by jdwisc** [comment]
Hi,

I was just wondering if you think this would be possible.  It would really benefit me and a lot of other people as well as I mainly choose 'Reply to All' and rarely only 'Reply'.

**Comment by Anindya007** [comment]
Hi,

I came up with the small code needed for the replyAll functionality mentioned above,Can I be assigned this enhancement?

This will be my first experience to contribute in any open source project

**Comment by Vikasg7** [comment]
@Anindya007 You can fork this repo and send a pull request. I might have assigned you but it's not showing your username in the assignee list. So just send a pull request. I will merge after review.
