### ISSUE TITLE
it looks like its no longer working

### ISSUE THREAD

**Issue by jad00gar** [Vikasg7/UnQuote-for-Gmail#10]
Hi,
I downloaded the extension but it looks like it's not working anymore.
because after sending an email when I check the quoted text is still in the email.

**Comment by Vikasg7** [comment]
@jad00gar 
It works, You gotta enable the extension by clicking on the `Click here to Enable` button in the extension popup and reload the Gmail page. Please make sure you let the Gmail page fully load up before clicking th 'Reply' button.
