### ISSUE TITLE
Does not function

### ISSUE THREAD

**Issue by manglewurzle** [Vikasg7/UnQuote-for-Gmail#12]
I'm running Chrome on Win 10 1909.  UnQuote does not remove the quoted email in my replies.
I have rebooted, stopped and restarted Windows all to no avail.

**Comment by Vikasg7** [comment]
@manglewurzle  
You can do/check following things:-  
1. Make sure to enable the extension by clicking the Extension Icon on the top right corner to the chrome.  
2. You have to wait for some time after Gmail page loads to let extension register its features.

**Comment by zongyan** [comment]
it seem that not working on Microsoft Edge (Version 91.0.864.41 (Official build) (64-bit)) running on Windows 10 21H1?
