### ISSUE TITLE
Feature suggestion: Start with the extension enabled

### ISSUE THREAD

**Issue by ArcWandx86** [Vikasg7/UnQuote-for-Gmail#13]
A common issue for many people seem to be a lack of reading comprehension, and thus they don't realize that they need to enable it. Why not stop these issues by starting with it enabled by default?

Sorry if this isn't feasible, I'm not familiar with js.

**Comment by Vikasg7** [comment]
Yes, agree with you. I think, changing following  
https://github.com/Vikasg7/UnQuote-for-Gmail/blob/a9401c762494f574a2b36f3df6e3a48314480d99/app/bg/bg.js#L3  
to  
````javascript
const isExtEnabled = localStorage.isExtEnabled ? JSON.parse(localStorage.isExtEnabled) : true
````  
should do it.  
But really, don't want to do all the steps from changing, testing, and publishing.  
People need the patience to use this extension, it may not work if you go fast through the emails, which may not let the extension register its handlers.
