### ISSUE TITLE
Add support for Forward and Reply All Buttons

### ISSUE THREAD

**Issue by Vikasg7** [Vikasg7/UnQuote-for-Gmail#14]
@AmyZern we can use this issue thread to check the progress of the new feature.

**Comment by Vikasg7** [comment]
Ok @AmyZern, This [commit](https://github.com/Vikasg7/UnQuote-for-Gmail/commit/1208347d68b47415cfc06bb10a1cfe06d7e9a062) adds support for Reply All and Forward buttons AND makes the extension for Robust and Miss-proof.  
Please update your extension to version 1.0.2, you might have to wait for a few days for the update to show up if you are using Microsoft Edge Browser.

**Comment by AmyZern** [comment]
Thank you!  That is so helpful for my job. Really. Thank you so much!
