### ISSUE TITLE
Unquote issue

### ISSUE THREAD

**Issue by Jumbocruiser** [Vikasg7/UnQuote-for-Gmail#15]
I find that if the other person replies and includes earlier communications (threads) that Unquote does not work.
It only seems to work on "virgin" replies.

Steve

**Comment by Vikasg7** [comment]
@Jumbocruiser I will look into it and push an update.

**Comment by Vikasg7** [comment]
@Jumbocruiser I updated the extension to fix the bug but in my testing, I couldn't reproduce the behavior you were pointing out. Please update the extension, re-test, and let me know.

Vikas

**Comment by Jumbocruiser** [comment]
Hi Vikas,

I will do as you ask when I get back (I am on holiday) and will report back
to you. At the moment the extension is not working at all !

Steve


* Stephen Lee - Jumbocruiser Limited +44 2036331951 x 2 *

**Comment by Vikasg7** [comment]
@Jumbocruiser Yes, pushed an update to fix just that.

**Comment by Jumbocruiser** [comment]
Hi Vikas - it is working well thank you.

If you want to hear a suggestion ?

In the old days in Gmail, you could highlight text with your mouse, hit
Reply, and only the text you highlighted would be included under your
reply.

That was a very useful feature.

Steve

* Stephen Lee - Jumbocruiser Limited +44 2036331951 x 2 *

**Comment by Vikasg7** [comment]
thanks for the suggestion, but this feature can't be covered in this extension. I think, if you are highlighting the text, you can simply copy and quote the text in your reply, that is one way.
