### ISSUE TITLE
Doesn't seem to work as of 2023-12-06

### ISSUE THREAD

**Issue by Teraskull** [Vikasg7/UnQuote-for-Gmail#16]
I tried enabling and disabling the extension, reinstalling it, and reloading the Gmail page.

It worked a few times, but does not anymore.

May it be because of some race conditions?

**Comment by Vikasg7** [comment]
Hi,  
It is working for me, and yes, there could be misses. A good practice is to let the web page fully load (until you don't see any yellow `Loading..` indicators on the top) before you click on individual emails to read/reply.  if there is a miss (most probably event listeners didn't register), you can go back to Inbox and click on the email again to trigger the event listeners.

Here is the control flow of the extension:
1. When you reload the Gmail page after installing the extension, it injects the content script.
2. When you click an individual email, HashChange Event activates and the event listener checks if it is an incoming Email, if not, `return` 
3. If yes, it adds event listeners to the reply/forward buttons on the page.
4. When you hit Reply/Forward, 
   - it will remove the quoted stuff and add your `signature` if any,
   - it will add event listeners to the discard/send buttons
5. When the discard/send buttons are clicked, The control flow GoTo step 3.
