### ISSUE TITLE
Typo in app/cs/cs.js

### ISSUE THREAD

**Issue by Anindya007** [Vikasg7/UnQuote-for-Gmail#3]
Hi,

This is a nifty extension to have and I like it.I can see that their is a typo in the cs.js file as the folllowing 

`window.removeEventListener("haschange", onHashChange)`

I was getting some errors in chrome console due to this. I fixed it to the following

`window.removeEventListener("hashchange", onHashChange)`

And the errors are gone for good.

Nevertheless,its a cool app for sure.

Regards,
Anindya

**Comment by Vikasg7** [comment]
@Anindya007 Send a pull request, I will review and merge. Thanks
