### ISSUE TITLE
No working with new Gmail view

### ISSUE THREAD

**Issue by adolfoovalles** [Vikasg7/UnQuote-for-Gmail#5]
This morning my gmail was force to use the new view appearance and the back to classic view was removed from the gear menu, since then the add-on stop doing its magic, yesterday was fine working perfectly!

I use OSX 10.10 yosemite. Chrome Versión 69.0.3497.100 (Build oficial) (64 bits), if you need more data let me know.

I really love your add-on, works perfectly and time saver, please let me know if you've found a way to make it work again, thanks!!!

**Comment by Vikasg7** [comment]
@adolfoovalles,
I pushed a new update for the new Gmail View and Also for the `Reply to all` button. Update your extension if isn't at v0.0.6.
