### ISSUE TITLE
Not working with current GMail and/or Chromium

### ISSUE THREAD

**Issue by peter-kehl** [Vikasg7/UnQuote-for-Gmail#8]
Dear Vikas,

Thank you for this extension.
It doesn't work for me. I tried several times.

![image](https://user-images.githubusercontent.com/4270240/52158984-45668b00-2653-11e9-9e0b-ab01814346af.png)

I disabled all other Chromium extensions, except for Unquote for GMail:
![image](https://user-images.githubusercontent.com/4270240/52158974-27992600-2653-11e9-8557-9641ea3a3860.png)

Since I use many GMail Labs, I run with and without them: https://mail.google.com/mail and https://mail.google.com/mail/u/0/?labs=0. No difference.

Whether i hit "Reply" or "Reply to all" button, or the reply icon, or an image of three three vertical dots > dropdown menu > "Reply" or "Reply to all":
![image](https://user-images.githubusercontent.com/4270240/52160642-95068000-266e-11e9-8732-fc30eb690246.png)
it always comes with the quote in the new draft: a picture of three horizontal dots that has mousover "Show trimmed content".

My Linux (Manjaro/Arch) doesn't currently let me run both Chromium and Google Chrome, I'm investigating. Could you clarify/advise in the meantime, please.

**Comment by Vikasg7** [comment]
I tested the extension on chromium and its working. You have to let the Gmail (Web page) fully load before opening the emails in the inbox and hit reply. Also if your pc is slow in opening the mails, it might not work as Extension expects reply buttons to load up before roughly 1 second after you open an email.

**Comment by peter-kehl** [comment]
Thank Vikas.
I confirm that it works in both Chrome and Chromium. Thank you.

1. After the user installed the extension, why do you require them to enable it? When I install something, I expect it to work straight away. Otherwise it's not obvious.

2. Could you document that it works only with GMail setting "Insert this signature before quoted text in replies and remove the "--" line that precedes it." enabled.

3. Any chance for it to work on the reply arrow-like mini button near the top right 
![image](https://user-images.githubusercontent.com/4270240/52237121-8e018c80-287d-11e9-9e97-7615cf36ab21.png), please?

**Comment by Vikasg7** [comment]
@peter-kehl 
> 1. After the user installed the extension, why do you require them to enable it? When I install something, I expect it to work straight away. Otherwise it's not obvious.  

That's because if extension starts messing up with the 'Reply Text', user can disable it instead of uninstalling it. On the next patch, extension will be updated and they don't have to install it again.

> 2. Could you document that it works only with GMail setting "Insert this signature before quoted text in replies and remove the "--" line that precedes it." enabled.  

I couldn't understand above question. 

> 3. Any chance for it to work on the reply arrow-like mini button near the top right
>    ![image](https://user-images.githubusercontent.com/4270240/52237121-8e018c80-287d-11e9-9e97-7615cf36ab21.png), please?  

No, because it will be make it more unstable as I have to register more handlers and it will also make the control flow cumbersome. Currently extension supports handlers on `Reply`, `Reply to All`, `Send` and `Discard` buttons. Also google developers might change the CSS selectors for these buttons which will break the extension. Hence I have kept the number of buttons affected short.

**Comment by peter-kehl** [comment]
Thank you.
My 2nd question was a mistake. All clear.
